### PR TITLE
update multivaluefield to latest 3.x version

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by xini** [comment]
Thanks Marcus. Can you please tag this as a release? Cheers

**Comment by nyeholt** [comment]
If you're locking your composer.json to a tilde minor version of the module (ie ~4.2), you should be able to composer update symbiote/silverstripe-multisites even without a tag.

**Comment by xini** [comment]
no. But "4.0.x-dev" does. I'd appreciate a stable tag though.

**Comment by nyeholt** [comment]
Okay have fixed up the discrepancy between branches and tags, so that the 4.0 branch is now actually up-to-date with where the 4.2.0 tag was, and have created a new tag 4.3.0 to match the version update in multivalue field.

**Comment by xini** [comment]
awesome! thanks so much!

**Pull request merged**
