### PR TITLE
[Fix] Publishing ErrorPages from wrong domain.

### PR DESCRIPTION
**Pull request by JoshuaCarter**
- Prevents publishing of an ErrorPage when logged in via another domain.
- Shows warning and disabled publish button when on another domain's ErrorPage.
- Extension type for MultisitesErrorPageExtension changes to 'Extension'.

### CODE REVIEW

**Comment by JoshuaCarter** [comment]
@nyeholt Looking at the failed test, it's not clear to me why it's failing. Point 3 on this PR is the only change I can picture causing any issues.

To preempt the question "why change it?"; because I couldn't see a reason for it to be a SiteTreeExtension. `updateErrorFilename` is still called on publish so everything should be fine, no?

**Comment by stephenmcm** [comment]
Related Issue #89

**Comment by nglasl** [comment]
I'm not sure I agree with the approach here.

1) We're adding our own custom button disabled state.
2) This feels like it introduces a poor user experience IMO. I could see somebody navigating to a page from the wrong domain and being frustrated because they can't publish it.
3) It seems like we're only working around the issue here. Perhaps there's a better approach that can be taken? For example, _**we**_ generate the error page asset correctly on publish?

@stephenmcm thoughts here?

**Comment by stephenmcm** [comment]
There's no graceful way of generating the static page. Under the covers SilverStripe uses [Director::mockRequest()]{https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Director.php#L164} to create the html before writing it to file. The effect of this is that we have to carefully overwrite anything that changes:

 - Base URL
 - Theme
 - Requirements

Generally speaking the way the page is generated doesn't lend itself well to be being faked on a different domain.  
The user experience is affected but error pages are a relatively stable page that generally only receive an initial set up.

**Comment by JoshuaCarter** [comment]
@stephenmcm how do you want to proceed with this?

**Pull request merged**
